# Generated by Django 2.2.4 on 2019-09-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speechtosign', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='SpeechToSign',
        ),
    ]
